<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Modulith.Worker-B94A4C8D-065C-4858-B603-125026C1F7C5</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.AspNetCore" Version="1.8.12" />
        <PackageReference Include="Hangfire.PostgreSql" Version="1.20.2" />
        <PackageReference Include="Hangfire.StackExchange.Redis" Version="1.9.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
        <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.19.6" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SharedKernel\Modulith.SharedKernel\Modulith.SharedKernel.csproj" />
      <ProjectReference Include="..\NewModule\Modulith.NewModule.Infrastructure\Modulith.NewModule.Infrastructure.csproj" />
    </ItemGroup>
</Project> 